-- Generated by scripts/sync-lockout-challenges.mjs from `supabase/seed/lockout-challenges.json` -- do not hand-edit.

insert into lockout_challenges (prompt, is_active)
values
  ('PLACEHOLDER: Take a photo with a street performer.', true),
  ('PLACEHOLDER: Find a mural and pose in front of it.', true),
  ('PLACEHOLDER: Order something in a language other than English.', true),
  ('PLACEHOLDER: Get a stranger to give you a high five.', true),
  ('PLACEHOLDER: Ride a cable car for at least three stops.', true),
  ('PLACEHOLDER: Take a photo at a scenic overlook.', true),
  ('PLACEHOLDER: Find a dog and learn its name.', true),
  ('PLACEHOLDER: Visit a bookstore and read the first page of a random book aloud.', true),
  ('PLACEHOLDER: Get a receipt with a total ending in .00.', true),
  ('PLACEHOLDER: Take a photo with a piece of public art.', true),
  ('PLACEHOLDER: Find a building built before 1920.', true),
  ('PLACEHOLDER: Buy the cheapest item on a menu.', true),
  ('PLACEHOLDER: Get a local to recommend their favorite coffee shop.', true),
  ('PLACEHOLDER: Take a photo of your team at a fountain.', true),
  ('PLACEHOLDER: Find a street named after a person.', true),
  ('PLACEHOLDER: Sketch the nearest storefront in under two minutes.', true),
  ('PLACEHOLDER: Find a payphone (or prove none exist nearby).', true),
  ('PLACEHOLDER: Get a photo with a bike messenger.', true),
  ('PLACEHOLDER: Visit a park bench and read its dedication plaque.', true),
  ('PLACEHOLDER: Find a restaurant with a hand-painted sign.', true),
  ('PLACEHOLDER: Take a group photo doing the same pose as a nearby statue.', true),
  ('PLACEHOLDER: Find three different languages on storefront signs within a block.', true),
  ('PLACEHOLDER: Get a barista to tell you their favorite drink.', true),
  ('PLACEHOLDER: Find a mailbox and note its collection time.', true),
  ('PLACEHOLDER: Take a photo with your team forming a human arrow pointing north.', true),
  ('PLACEHOLDER: Find a plaque or marker commemorating a historical event.', true),
  ('PLACEHOLDER: Get a stranger to recommend a nearby hidden gem.', true),
  ('PLACEHOLDER: Find a store that has been open more than 25 years.', true),
  ('PLACEHOLDER: Take a photo of the whole team mid-jump.', true),
  ('PLACEHOLDER: Find a crosswalk button and time how long the wait is.', true)
on conflict (prompt) do update set is_active = true;

-- Soft-retire anything no longer in the file (never hard-deleted --
-- lockout_cells may still reference it from a past game).
update lockout_challenges
set is_active = false
where is_active = true
  and prompt not in (
    'PLACEHOLDER: Take a photo with a street performer.',
    'PLACEHOLDER: Find a mural and pose in front of it.',
    'PLACEHOLDER: Order something in a language other than English.',
    'PLACEHOLDER: Get a stranger to give you a high five.',
    'PLACEHOLDER: Ride a cable car for at least three stops.',
    'PLACEHOLDER: Take a photo at a scenic overlook.',
    'PLACEHOLDER: Find a dog and learn its name.',
    'PLACEHOLDER: Visit a bookstore and read the first page of a random book aloud.',
    'PLACEHOLDER: Get a receipt with a total ending in .00.',
    'PLACEHOLDER: Take a photo with a piece of public art.',
    'PLACEHOLDER: Find a building built before 1920.',
    'PLACEHOLDER: Buy the cheapest item on a menu.',
    'PLACEHOLDER: Get a local to recommend their favorite coffee shop.',
    'PLACEHOLDER: Take a photo of your team at a fountain.',
    'PLACEHOLDER: Find a street named after a person.',
    'PLACEHOLDER: Sketch the nearest storefront in under two minutes.',
    'PLACEHOLDER: Find a payphone (or prove none exist nearby).',
    'PLACEHOLDER: Get a photo with a bike messenger.',
    'PLACEHOLDER: Visit a park bench and read its dedication plaque.',
    'PLACEHOLDER: Find a restaurant with a hand-painted sign.',
    'PLACEHOLDER: Take a group photo doing the same pose as a nearby statue.',
    'PLACEHOLDER: Find three different languages on storefront signs within a block.',
    'PLACEHOLDER: Get a barista to tell you their favorite drink.',
    'PLACEHOLDER: Find a mailbox and note its collection time.',
    'PLACEHOLDER: Take a photo with your team forming a human arrow pointing north.',
    'PLACEHOLDER: Find a plaque or marker commemorating a historical event.',
    'PLACEHOLDER: Get a stranger to recommend a nearby hidden gem.',
    'PLACEHOLDER: Find a store that has been open more than 25 years.',
    'PLACEHOLDER: Take a photo of the whole team mid-jump.',
    'PLACEHOLDER: Find a crosswalk button and time how long the wait is.'
  );
